export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_MEMBER_UPDATE = 'AUTH_MEMBER_UPDATE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';

export const ADD_APP = 'ADD_APP';
export const DELETE_APP = 'DELETE_APP';
export const EDIT_APP = 'EDIT_APP';
export const GET_APP = 'GET_APP';
export const GET_APPS = 'GET_APPS';
export const CLEAR_APPS = 'CLEAR_APPS';

export const ADD_CLIENT = 'ADD_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENTS = 'GET_CLIENTS';
export const CLEAR_CLIENTS = 'CLEAR_CLIENTS';

export const ADD_MEMBER = 'ADD_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const EDIT_MEMBER = 'EDIT_MEMBER';
export const GET_MEMBER = 'GET_MEMBER';
export const GET_MEMBERS = 'GET_MEMBERS';
export const CLEAR_MEMBER = 'CLEAR_MEMBER';

export const ADD_ERROR = 'ADD_ERROR';
export const DELETE_ERROR = 'DELETE_ERROR';
export const EDIT_ERROR = 'EDIT_ERROR';
export const GET_ERROR = 'GET_ERROR';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const ADD_PROFILE = 'ADD_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const CLEAR_PROFILES = 'CLEAR_PROFILES';

export const ADD_LICENSEKEY = 'ADD_LICENSEKEY';
export const DELETE_LICENSEKEY = 'DELETE_LICENSEKEY';
export const EDIT_LICENSEKEY = 'EDIT_LICENSEKEY';
export const GET_LICENSEKEY = 'GET_LICENSEKEY';
export const GET_LICENSEKEYS = 'GET_LICENSEKEYS';
export const CLEAR_LICENSEKEYS = 'CLEAR_LICENSEKEYS';

export const ADD_LICENSEKEYASSIGNMENT = 'ADD_LICENSEKEYASSIGNMENT';
export const DELETE_LICENSEKEYASSIGNMENT = 'DELETE_LICENSEKEYASSIGNMENT';
export const EDIT_LICENSEKEYASSIGNMENT = 'EDIT_LICENSEKEYASSIGNMENT';
export const GET_LICENSEKEYASSIGNMENT = 'GET_LICENSEKEYASSIGNMENT';
export const GET_LICENSEKEYASSIGNMENTS = 'GET_LICENSEKEYASSIGNMENTS';
export const CLEAR_LICENSEKEYASSIGNMENTS = 'CLEAR_LICENSEKEYASSIGNMENTS';
